name: Deploy Hostings

on:
  push:
    branches:
      - master
    paths:
      - 'hosting/**'
      - '.github/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Run Eslint
        run: |
          cd hosting
          yarn
          yarn lint
      - name: Deploy hosting
        run: |
          cd hosting
          yarn
          yarn build
          export FIREBASE_TOKEN=${{ secrets.FIREBASE_TOKEN }}
          yarn deploy
