name: Deploy Functions

on:
  push:
    branches:
      - master
    paths:
      - 'functions/**'
      - '.github/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 
        uses: actions/setup-node@v2
        with:
          node-version: 8.x
      - name: Run Eslint
        run: |
          cd functions
          yarn
          yarn lint
      - name: Deploy functions
        run: |
          cd functions
          yarn
          export FIREBASE_TOKEN=${{ secrets.FIREBASE_TOKEN }}
          yarn deploy
